# Generated by Django 5.2 on 2025-04-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividade_app', '0003_alter_usuario_email_alter_vendedor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
    ]
