# Generated by Django 5.2 on 2025-04-26 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atividade_app', '0004_alter_usuario_email_alter_vendedor_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='name',
            new_name='nome',
        ),
    ]
